---
title: ".b[Economic Growth: Discussions]"
subtitle: ".b[.green[EC 103--002]]"
author: "Marcio Santetti"
date: "Fall 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'skid-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: "16:9"
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(broom, latex2exp, ggplot2, ggthemes, ggforce, viridis, dplyr, magrittr, knitr, parallel, xaringanExtra, tidyverse, sjPlot, showtext, mathjaxr, ggforce, furrr, kableExtra, wooldridge, hrbrthemes, scales, ggeasy, patchwork, readxl, MetBrewer)




# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F,
  dpi=300
)

theme_set(theme_ipsum_rc())

```



# Motivation


---

# Motivation

One of my promises in the beginning of the semester was that not only will we learn (macro)economic concepts, but also evaluate these concepts through .hi[data] and by looking at .hi-orange[the news].

--

Regarding the first, we have finally started manipulating economic data in RStudio (more stuff to come).

--

<br>

Now, to the second!

  - It is time to look at some news pieces and make sense of it.
  
  - By this time, do not expect to understand every single term, but with what you have learned so far, we can start some .hi[in-class discussions].

---

# Group discussions

A few pieces:

<br>

1. [`Global growth is slowing, but not stopping—yet`](https://archive.ph/20220515211547/https://www.economist.com/finance-and-economics/2022/05/15/global-growth-is-slowing-but-not-stopping-yet#selection-563.0-563.46);

2. [`Why long-term economic growth often disappoints`](https://archive.ph/20220505125235/https://www.economist.com/finance-and-economics/2022/05/07/why-long-term-economic-growth-often-disappoints#selection-571.0-571.47);

3. [`Economic growth at all costs: what is the trade-off?`](https://impact.economist.com/sustainability/circular-economies/economic-growth-at-all-costs-what-is-the-trade-off);

4. [`America’s economy will claw its way back to the pre-covid trend`](https://archive.ph/20211209125244/https://www.economist.com/the-world-ahead/2021/11/08/americas-economy-will-claw-its-way-back-to-the-pre-covid-trend);

5. [`Is low economic growth a sign of success?`](https://archive.ph/20200608054408/https://www.economist.com/finance-and-economics/2020/01/23/is-low-economic-growth-a-sign-of-success#selection-617.0-617.41)


---

# Group discussions

.smaller[Guidelines:

  - For .hi[Thursday] (09/29), 5 groups will pick one piece each.
  
  - Each group will discuss their readings and share their thoughts with everyone.
  
  - Some suggested topics:
  
    - What is the piece *about*?
    - What is the *main* argument?
    - What did you *not* understand (probably because it has to do with an upcoming class topic)?
    - How did the piece make you reflect about *economic growth*?
    - *Any other point(s)* that you see fit.


Each group will have about .hi-orange[10 minutes]. Then, we may have a couple of questions/comments from the classroom community.

Each group may have a *speaker*, or *tag-team* if you prefer. Just be mindful of .hi[time management].

.hi[No] formal presentations needed. We will only share some thoughts and ideas.
]

---
# Group discussions

<br>

Each group member will be graded equally for their expositions.

--

<br>

This discussion will cover the .hi[*Reflection*] section of Problem Set 2.

--

<br><br>

Questions?


---

layout: false
class: inverse, middle

# Next time: Unemployment


---
exclude: true
