---
title: ".b[All-things 'capitalism,' pt. II]"
subtitle: ".b[.green[EC 103--002]]"
author: "Marcio Santetti"
date: "Fall 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'skid-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: "16:9"
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(broom, latex2exp, ggplot2, ggthemes, ggforce, viridis, dplyr, magrittr, knitr, parallel, xaringanExtra, tidyverse, sjPlot, showtext, mathjaxr, ggforce, furrr, kableExtra, wooldridge, hrbrthemes, scales, ggeasy, patchwork, MetBrewer, readxl)




# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F,
  dpi=300
)

theme_set(theme_ipsum_rc())

```



# Motivation

---

# Motivation

<br>

Suppose you end up with a *flat tire* in the middle of Wisconsin while taking a road trip.


<br>
--

  - What is your .hi-orange[first] action? [call on other members of the community; plumbing; IT issues.]



[tasks we cannot perform are done by others near us; if not physically, immediate e.g. Amazon.]

---

# Motivation

Since tasks we cannot do ourselves can be performed by others, the .hi[guaranteeing of the daily bread] is secured to a wide range of .hi-orange[economic agents].

--

<br>

  - *What are these agents*?


  
--

  - Households;
  - Firms;
  - Government;
  - Law enforcement.
  
--

<br>

Therefore, the material abundance we know today is a product of the .hi[division of labor].

.small[[Material abundance is only possible due to a social cooperation process that occurs independently of our own actions. So there is a connection bw individual and society as a whole]]

---

layout: false
class: inverse, middle

# The individual and society

---

# The individual and society

Over the course of economic progress, the division of labor has allowed economies to improve technology, productivity, and the well-being of society.

--

Along with this, so have improved the .hi-orange[reach of human wants].

--

And this progress comes at the expense, primarily, of .hi[nature].

--

Thus, .hi-orange[scarcity] is not only a feature of *nature*, but also created and intensified by *humans.*

<br>

--

The "*standard*" definition of Economics usually gravitates around the lines of

  > *Allocating scarce resources among finite ends*.
  
--

.right[*Do you agree*?]
  



---

# The individual and society

Regardless of the social system, .hi[any] economy must solve two .hi-orange[fundamental tasks] to function:

--

<br>

  1. .hi[Production];
  2. .hi[Distribution].
  
<br>
  
--

Regarding .hi[1], a society must provide enough goods and services to guarantee its survival.

--

And after output is produced, how to .hi-orange[arrange the circulation] of whats is produced?

--

<br>

Although simple *intuitively*, in *practice* these two tasks are quite .hi[complicated].


---

# The individual and society

<br>

Most of the times, nature does not give humans the finished products for their consumption.

--

Thus, some process(es) of .hi-orange[material transformation] is necessary.

--

<br>

  - The process of .hi[production], therefore, involves *organizing the social institutions that will mobilize efforts to advance these material transformations*.
  
  
[but how come poor nations that are rich in natural resources remain poor?]

<br>

  - *What to produce?*
  - *How much to produce?*
  - *And produce to whom?*

---

# The individual and society


After these decisions are made, the problem becomes how to .hi[distribute] the fruits of human productive effort.

--

And the .hi-orange[strategy] to distribute output must keep individuals constantly engaged in production.

[social/political unrest]

---

# The individual and society

.hi[How] to produce and distribute?

--

<br>

Throughout History, we have experiences .hi[three] main types of .hi-orange[solutions] to the production and distribution issues.

--

<br>

These are:

  1. *Tradition*;
  
  2. *Command*;
  
  3. *The market*.


---

layout: false
class: inverse, middle

# Solutions to the economic problem


---

# Solutions to the economic problem

Let us start with .hi[tradition].

--

Over a long process of trial and error, *tradition* is established as a mode of organization based on .hi-orange[custom] and .hi[belief].

--

Usually, tradition assigns .hi[production] tasks to fathers and sons.

[Egypt; agricultural families, craftsmen].

--

And .hi-orange[kinship] regulates the .hi[distribution] process.

--

<br>

Tradition however, lacks .it[dynamism.]

  - Unable to produce in *larger scales*.
  
  
---

# Solutions to the economic problem

.hi[Command] is a method of .hi-orange[imposed authority].

--

In this setting, .hi[production] and .hi[distribution] occur according to .it[authoritarian] enforcement.

[slavery, empire, monarchs, dictatorships. but also in times of natural disasters, pandemics.]

---

# Solutions to the economic problem

<br>

Lastly, the .hi[market] has no deep ties with either *tradition* or *command*.

--

<br>

How .hi[production] and .hi[distribution] are (dis)organized will depend on different points in time and locations.

--

<br>

And to better understand this puzzle we have to go back in History and see the main differences between .hi-orange[pre-market] and .hi[market] societies.




---
layout: false
class: inverse, middle

# Pre-market societies

---

# Pre-market societies


---

# Pre-market societies



---

# Pre-market societies


---

layout: false
class: inverse, middle

# The emergence of markets


---

# The emergence of markets


---

# The emergence of markets


---

# The emergence of markets


---

# The emergence of markets



---

layout: false
class: inverse, middle

# Next time: Technology, population, and growth


---
exclude: true