---
title: ".b[Money supply & demand, pt. II]"
subtitle: ".b[.green[EC 103--02]]"
author: "Marcio Santetti"
date: "Fall 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'skid-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: "16:9"
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(broom, latex2exp, ggplot2, ggthemes, ggforce, viridis, dplyr, magrittr, knitr, parallel, xaringanExtra, tidyverse, sjPlot, showtext, mathjaxr, ggforce, furrr, kableExtra, wooldridge, hrbrthemes, scales, ggeasy, patchwork,
       ggrepel)




# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F,
  dpi=300
)

theme_set(theme_ipsum_rc())

```



# Motivation



---

# Housekeeping

<br>

.b[Required readings]:

  - Colander (2010), ch. 13.
  
    - See *Extra Readings* module on `theSpring`.
    
  - [`The $24 Trillion Market That Predicts and Influences Interest Rates (NYT)`](https://archive.ph/20221103022329/https://www.nytimes.com/2022/11/02/business/treasury-yields-bond-market.html)



---


layout: false
class: inverse, middle

# The demand for money


---

# The demand for money

Last time, we formalized some ideas about .hi[money].

--

After discussing its main .hi-orange[functions] and how banks .hi[create] it, we turn to the "*other side"* of the story:

--

  - *Why do people hold (demand) money?*
  
--

<br>

Before looking for potential answers to this question, one .hi-orange[crucial] point:

  - Holding (liquid) money does not pay *any* .hi[interest], whereas other .hi-orange[financial assets] do.
  
--

<br>

In other words, why not put some money in a *certificate of deposit*; buy *stocks*, *bonds*, etc?

---

# The demand for money

Since by holding money people are *forgoing* interest payments, there must be .hi[benefits] associated with it.

--

<br>

In fact, these potential benefits can be summarized by three .hi[motives]:

  1. *Transactions* motive;
  
  2. *Precautionary* motive;
  
  3. *Speculative* motive.
  
--

<br>

These motives were formalized by *J.M. Keynes* in 1930 and 1936.


---

# The demand for money

Starting with the .hi-orange[transactions] motive, holding money allows people to purchase things.

--

  - *Pure and simple*.
  
--

There is no way to go to the store and pay your groceries with a U.S. government bond certificate, for example.

--

<br>

In line with this first motive, holding cash balances is also a .hi[precautionary] move.

--

  - People hold money for *emergencies*, *unexpected expenses*, and *impulse buying* events.
  
--

<br>

While the greatest portion of our regular expenditures are expected, there is always some .hi-orange[uncertainty] associated with spending.

---

# The demand for money

Lastly, the final reason for holding money is the so-called .hi[speculative] motive.

--

And this motive lies at the heart of the *trade-off* between cash and other interest-paying .hi-orange[financial assets].

--

This motive comes about due to the *varying* nature of .hi[interest rates] (yields) for bonds, stocks, and other potential allocations of our money holdings.

--

<br>

Thus, if one expects the price of a bond&mdash;or any financial asset&mdash;to *fall*, they will be *losing* money by having it.

--

Although having money in the wallet *does not* pay any interest, at least there is *no loss* by doing so.

---

# The demand for money

<br><br>

The *key* idea behind the .hi[speculative] motive is that one *speculates* about what the future value of a financial asset will be.

--

<br>

  - If asset prices are expected to *rise*, it is *rational* to reduce liquid money holdings;
  
  - If asset prices are expected to *fall*, the rational thing to do is to *hold* cash balances.

---

layout: false
class: inverse, middle

# Money demand & interest rates


---

# Money demand & interest rates

The speculative motive gives us a great opportunity to study in more depth the relationship between .hi[money demand] and .hi-orange[interest rates].

--

But before that, let us *clarify* some terms.

--

Starting with an .hi[asset], we have .hi-orange[real] and .hi-orange[financial] assets:

  - A .hi[real asset] is something one expects to receive income or services from, since one can use it in some way that will benefit them.
  
    - A house, a machine, an automobile, a building,...
    
--

  - On the other hand, a .hi-orange[financial asset] does not involve concrete ownership, but a promise of future payment by someone (something) else.
    -  *Stocks* and *bonds* are the most common types of financial assets.
    

---

# Money demand & interest rates

Every financial asset has a corresponding .hi[financial liability].

--

Every issuer of a financial asset has to *stand behind* its financial asset, thus promising to pay interest/dividend and its principal.

  - This gives .hi-orange[value] to a financial asset.
  
--

<br>

A .hi[stock] is a financial asset that carries ownership rights in a firm. 

  - Owning a stock usually conveys the right to .hi[dividends].
  
--

<br>

A .hi-orange[bond] is a financial asset that involves promises to pay certain amounts of money (coupon) at specified future periods over the bond's maturity.
---

# Money demand & interest rates

Let us take .hi[bonds] as a *reference* for financial assets.

--

Suppose you have a 2-year .b[$500] bond, paying a coupon rate of .b[10%] per year. 

--

Given that this asset is a promise of future payment at the end of this maturity period, in 2 years you will end up with .b[$600].

--

When you purchased the bond, the prevailing interest rate in the economy was 10%.

--

<br>

Then, after some time, the economy's interest rate rises to .hi[15%].

--

  - What happens to the price of your financial asset?

---

# Money demand & interest rates

<br>

If a second investor purchases a bond similar to yours&mdash;but with the new coupon rate&mdash;, they will end up with .b[$650] after its maturity period.

--

Therefore, your bond has .hi[lost value].

--

<br>

In case you want to .hi-orange[sell] your bond, other investors will be willing to pay .hi[less] than what you've paid for it, given that the new prevailing interest rate has risen.

---

# Money demand & interest rates

Now, what if the interest rate had fallen to, say, .b[5%]?

--

If a second investor purchases a bond similar to yours&mdash;but with this new coupon rate&mdash;, they will end up with .b[$550] after its maturity period.

--

<br>

In case you want to .hi-orange[sell] your bond, other investors will be willing to pay .hi[more] than what you've paid for it, given that the new prevailing interest rate has fallen.

---

# Money demand & interest rates

Summing up, when the interest rate *rises*, the price of existing bonds *falls.*

--

And when the interest rate *falls*, the price of existing bonds *rises.*

--

<br>

We may use the following formula for the price of a bond:

<br>

$$
\begin{aligned}
\text{Price of a bond} = \dfrac{\text{Face value} + \text{Coupon payment}}{(1 + \text{interest rate})^\text{maturity period}}
\end{aligned}
$$
---

# Money demand & interest rates

From our example, 


  - When the interest rate rises to 15%:
  
<br>

$$
\begin{aligned}
\text{Price of a bond} = \dfrac{\text{Face value} + \text{Coupon payment}}{(1 + \text{interest rate})^\text{maturity period}} = \dfrac{500 + 100}{(1 + 0.15)^2} = 453.68
\end{aligned}
$$
--

<br>

  - When the interest rate falls to 5%:
  
<br>

$$
\begin{aligned}
\text{Price of a bond} = \dfrac{\text{Face value} + \text{Coupon payment}}{(1 + \text{interest rate})^\text{maturity period}} = \dfrac{500 + 100}{(1 + 0.05)^2} = 544.21
\end{aligned}
$$


---

# Money demand & interest rates


In reality, interest rates .hi[fluctuate] all the time.

--

Bond investors continually look for hints/clues/information on what future interest rates will look like to decide on whether they should keep their investments or hold liquid money instead.

--

<br>

  - When individuals expect bond prices to .hi[rise], they hold .hi-orange[less] cash and *purchase* bonds.
  
  - When individuals expect bond prices to .hi[fall], they hold .hi-orange[more] cash and *sell* bonds.


--


<br>

These dynamics summarize the speculative motive for demanding money.



---

layout: false
class: inverse, middle

# Interest rate salad


---

# Interest rate salad

<br><br>

In reality, as there are *several* types of f*inancial assets*, there are several .hi[interest rates].

--

<br>

Although there are many different interest rates in the economy, they tend to move up or down with one another. 

--

<br>

Let us see some of them.
---

# Interest rate salad


- .hi[Three-month treasury bill rate (T-bill)]:

This is the "baseline" short-term interest rate in the U.S. economy. It consists of the interest rate paid on government bonds that mature in less than a year.

[`Data`](https://fred.stlouisfed.org/series/DTB3)

<br>


- .hi[Federal funds rate]:

The rate banks with excess reserves use to lend some of these reserves to other banks overnight. This is the rate addressed by the FED whenever its target interest rate changes.

[`Data`](https://fred.stlouisfed.org/series/DFF)

---

# Interest rate salad

- .hi[Prime rate]:

A *benchmark* rate that banks use to quote interest rates for different customers. Corporations/individuals with low risk may borrow at the prime rate, while higher risk individuals will be able to borrow at the prime rate *plus* some added fraction.

[`Data`](https://fred.stlouisfed.org/series/DPRIME)

<br>

- .hi[Commercial paper rate]:

Large firms may issue short-term financial assets offering a designated interest rate. Its value will depend on the firm's financial conditions and on the bond's maturity period.

[`Data`](https://fred.stlouisfed.org/series/DCPN2M)


---

# Interest rate salad

<br>

- .hi[AAA corporate bond rate]:

Bond dealers classify corporate bonds according to their risk. These are classified as *AAA*, *AA*, and so on. A bond with an *AAA* rating will reflect a rate that less risky firms pay on their issued bonds. 

[`Data`](https://fred.stlouisfed.org/series/AAA)

--


<br>

For more interest rate instruments and maturity periods, see [`here`](https://fred.stlouisfed.org/release/tables?rid=18&eid=289#snid=297).

---

layout: false
class: inverse, middle

# Next time: Open-economy macro

---
exclude: true