---
title: ".b[International trade & globalization, pt. I]"
subtitle: ".b[.green[EC 103--02]]"
author: "Marcio Santetti"
date: "Fall 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'skid-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: "16:9"
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(broom, latex2exp, ggplot2, ggthemes, ggforce, viridis, dplyr, magrittr, knitr, parallel, xaringanExtra, tidyverse, sjPlot, showtext, mathjaxr, ggforce, furrr, kableExtra, wooldridge, hrbrthemes, scales, ggeasy, patchwork,
       ggrepel)




# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F,
  dpi=300
)

theme_set(theme_ipsum_rc())

```



# Motivation



---

# Housekeeping

<br>

.b[Required readings]:

  - [`Openstax, ch. 16`](https://openstax.org/books/principles-macroeconomics-2e/pages/16-introduction-to-exchange-rates-and-international-capital-flows)
  
    - Sections 16.1 & 16.4
---

# "Open" macroeconomics

<br>

No single economy works in a .hi-orange[vacuum].

--

Events (*economic or not*) that happen in one country can have varied .hi[repercussions] on other parts of the world.

--

Each day, .hi[billions] of dollars of goods, services, and financial assets flow from one country to another in the .hi-orange[international trade market].

--

  - *But why do countries trade with each other?*
  

Either because they .hi[cannot] produce these goods and services by themselves, or due to other countries having .hi-orange[lower costs] at producing some goods and services (so importing them is cheaper).



---

# "Open" macroeconomics


From a *macroeconomic* perspective, purchasing a domestically-produced item or importing the same item are .hi[not] that different.

  - The main difference between these two transactions is .hi-orange[currency exchange].
  
    - While a *domestic* transaction is paid for with *domestic* currency, an *international* transaction must happen by using *exchange rates*.
    
--

When the United Kingdom imports bananas from Ecuador, the Ecuadorian exporters .hi[cannot] spend *pounds* in Ecuador.

The same happens when the US sells tractors to England. US residents .hi-orange[cannot] pay their rents using *pounds.*


--

> The .hi[exchange rate] is the *price* of one country's currency in terms of another country's currency. It is the *ratio* at which two currencies are traded for each other.


---

layout: false
class: inverse, middle

# Exchange rates

---

# Exchange rates

<br>

A .hi[nominal] exchange rate between two countries tells us .hi-orange[how many units] of the *first* country's currency one can buy for 1 unit of the *second* country's currency.

--

  - *Ordering matters!*



<br>

As an example, consider the US dollar-per-pound exchange rate. If its value is 2 US dollars per pound, it means that 1 pound is worth 2 US dollars.

Conversely, we can also say that 1 US dollar is worth 0.5 pound.

---

# Exchange rates

<br><br><br>

[`A quick Google search...`](https://www.google.com/search?q=1+pound+dollar&oq=1+pound+dolla&aqs=chrome.0.0i512j69i57j0i512l4j0i22i30l4.101506j1j4&sourceid=chrome&ie=UTF-8)


--


<br><br>

[`Has it always been this way?`](https://fred.stlouisfed.org/series/DEXUSUK)

---

# Exchange rates

If we use *E* to represent exchange rates, we can use the following *notation*:

<br>

.center[
*E<sub>a/b</sub>*
]

<br>

Reading it as "*the exchange rate in currency _a_ per 1 unit of currency _b_.*"

--

For instance, the *US dollar-per-euro* exchange rate is .b[0.99].

--

We can write it as *E<sub>US$/e</sub>* = 0.99.

  - Meaning that one euro is worth .99 US dollars.
  
  - So what is *E<sub>e/US$</sub>*?

---

# Exchange rates

When analyzing prices of regular goods and services, we say that a price has either *increased* or *decreased*.

--

  - With exchange rates, the .hi[terminology] is a bit different.
  
--


We say that a country's currency .hi[appreciates] when one unit of that currency can buy .hi-orange[more] units of a foreign currency than before.

  - Some may say that the currency became "*stronger*."

--

And a country's currency is .hi[depreciating] when one unit of that currency can buy .hi-orange[less] units of a foreign currency than before.

  - Some may say that the currency became "*weaker*."

--

An *appreciation* of one currency is the .hi-orange[same] as a *depreciation* of the other currency.


---

# Exchange rates

<br><br><br>

[`A look at the data`](https://fred.stlouisfed.org/series/DEXUSEU)



---

# Exchange rates

<br><br><br>

To summarize:


   - When *E<sub>a/b</sub>* goes up, currency *b* .hi[appreciates], and currency *a* .hi-orange[depreciates].
   
   - When *E<sub>a/b</sub>* goes down, currency *b* .hi[depreciates], and currency *a* .hi-orange[appreciates].



---

# Exchange rates

Who *benefits* from a .hi[stronger] (i.e., appreciated) currency?

--

Let us take the example of an .hi-orange[appreciation] of the *US dollar* relative to other international currencies.

--

In the case of:

  1. US exporters selling abroad;
  
  2. International firms selling to the US economy;
  
  3. US tourists abroad;
  
  4. Foreign tourists visiting the US;
  
  5. US investors considering investment opportunities abroad;
  
  6. Foreign investors considering injecting money in the US economy.
  

---

# Exchange rates

<br><br>

Moral of the story:

<br>

When thinking about exchange rates, a .hi[stronger] currency is *not necessarily* a good thing.

--

  - It will depend on the *sector* and on the *economic activity* at hand.

---

layout: false
class: inverse, middle

# Exchange rate policies

---

# Exchange rate policies

The way in which countries set the .hi-orange[value] of their currencies internationally can differ substantially.

--

When national governments .hi-orange[set] a country's exchange rate, we call it a .hi[fixed exchange rate].

  - And instead of talking in terms of *appreciation* or *depreciation*, we say that the government has engaged in *revaluation* and *devaluation* policies, respectively.
  
--

<br>

If, instead, the government does not intervene in the exchange rate, it will be determined by .hi[market demand] for the national currency.

  - In practice, the so-called .hi[foreign exchange market] is where those who desire to use one currency to buy a different one will privately trade with those who can sell the currency they desire.
  
--
  
  - When this is the case, we have .hi-orange[floating exchange rates].

---

# Exchange rate policies


Let us focus on .hi[floating exchange rates] first.

--

There are .hi-orange[three] main reasons to buy a foreign currency:

  1. For purchasing .hi[goods/services] from another country, where that other currency is used;
  
  2. For buying .hi-orange[assets] (financial or not), thus receiving income from it in the local currency;
  
  3. For .hi[holding] the currency, hoping that it will increase in value (appreciate) at some point.

--

Thus, currency demand may happen in the markets for .hi[goods and services], for .hi-orange[assets], and in the .hi[foreign exchange] market.

--

In *any* of these markets, exchange rates will change whenever there are opportunities for .hi-orange[arbitrage].

--

> .hi[Arbitraging] implies buying something where/when it is cheap, and selling when/where it becomes more expensive.

---

# Exchange rate policies

<br><br>


Thus, a currency will .hi[appreciate] when there is .hi-orange[higher demand] for it, relative to other currencies.

--

<br>

Conversely, a currency will .hi-orange[depreciate] when there is .hi[lower demand] for it.




---

# Exchange rate policies


No theory can explain with .hi[precision] what exchange rates will look like over any time horizon.

--

However, there are .hi-orange[tendencies].

<br>

--

For instance, in the .hi[goods/services] market, a country whose goods and/or services have a higher quality or are relatively cheaper&mdash;due to higher productivity or lower labor costs&mdash;will see its currency .hi-orange[appreciate] over time.

Thus, consumers look at .hi-orange[relative prices].

  - More .hi[demand] for its currency, to purchase it products &rarr; higher .hi-orange[value] &rarr; currency .hi[appreciation].
  
--

<br>

Countries that run a .hi[trade surplus] tend to see their currencies appreciate over time.

---

# Exchange rate policies

In the .hi-orange[asset market], how much foreign investors will spend in another country depends on its .hi[attractiveness].

--

In general, investors look for assets with the highest financial returns possible, so they will look at the country's .hi[interest rates].

--


<br>


Of course, .hi-orange[other factors] also matter for investment decisions abroad.

  - Safety, liquidity, tax regulations, etc.



---

# Exchange rate policies

Lastly, exchange rates are also driven by .hi[speculation] in foreign exchange markets.

--

> .hi-orange[Speculation] implies purchasing  assets with the goal of *reselling* them in the future, at a higher price.

--

<br>

Several participants in the foreign exchange market are *speculators.*

  - They hold foreign currencies in order to sell them when they appreciate.


--


For instance, if a Brazilian speculator bought US dollars in 2012, paying 2.15 BRL for US$ 1, today this 1 dollar will be sold by 5.31 BRL.

--

International assets (e.g., stocks and bonds) are traded at a high volume every day, making daily exchange rates basically .hi[unpredictable].




---

layout: false
class: inverse, middle

# Next time: Trade balances; balance of payments

---
exclude: true