---
title: ".b[International trade & globalization, pt. II]"
subtitle: ".b[.green[EC 103--02]]"
author: "Marcio Santetti"
date: "Fall 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'skid-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: "16:9"
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(broom, latex2exp, ggplot2, ggthemes, ggforce, viridis, dplyr, magrittr, knitr, parallel, xaringanExtra, tidyverse, sjPlot, showtext, mathjaxr, ggforce, furrr, kableExtra, wooldridge, hrbrthemes, scales, ggeasy, patchwork,
       ggrepel)




# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F,
  dpi=300
)

theme_set(theme_ipsum_rc())

```



# Motivation



---

# Housekeeping

<br>

.b[Required readings]:

  - [`OpenStax, ch. 10`](https://openstax.org/books/principles-macroeconomics-2e/pages/10-introduction-to-the-international-trade-and-capital-flows)
  
    - Sections `10.1`, `10.2`, and `10.3`.

  - [`Financial markets enter a dangerous new phase`](https://archive.ph/20220930115859/https://www.economist.com/finance-and-economics/2022/09/26/financial-markets-enter-a-dangerous-new-phase#selection-593.0-593.45)
  
  - [`Economists now accept exchange-rate intervention can work`](https://archive.ph/20220929174428/https://www.economist.com/finance-and-economics/2022/09/29/economists-now-accept-exchange-rate-intervention-can-work)


---

# Exchange rate demand & supply


We saw that, in a .hi[floating] exchange rate regime, the value of an exchange rate is determined by its .hi-orange[demand].

--

This demand may take place in the .hi-orange[goods] market, in the .hi[asset] market, and in the .hi-orange[foreign exchange] market.

--


But where does the .hi[supply] of foreign exchange come from?


--

Foreign currencies are supplied by foreign *households*, *firms*, and *governments* who want to purchase goods, services, and assets in the local currency. 

  - If a Swedish bank wants to purchase US government bonds, it first must *sell* Swedish kronas, and exchange it for US dollars. 
  
  - This way, Swedish kronas are *supplied* in the foreign exchange market, as US dollars are *demanded.*


---

# Exchange rate demand & supply


Thousands of transactions like the ones we've explored so far happen on a daily basis in the international trade market, influencing  a country's GDP.

--

But how are these transactions recorded?

--

  - Through a country's .hi[balance of payments].
  
--

<br>

> The .hi-orange[balance of payments] records a country's transactions in goods, services, and assets with the rest of the world. It also records a country's supply and demand of foreign exchange.

--

The balance of payments has two main components:

  - The .hi[current] account;
  
  - The .hi-orange[financial] account.
  

---

layout: false
class: inverse, middle

# The balance of payments


---


# The balance of payments


Let us start with the .hi[current] account.

--

<br>

The current account has .hi-orange[four] components:

  - (1): *Exports* of goods and services;
  
  - (2): *Imports* of goods and services;
  
  - (3): *Income* transfers and payments;
  
  - (4): *Unilateral* transfer payments.
  
  


---


# The balance of payments


(1) .hi[Exports] include goods and services *sold* to the rest of the world.

--

(2) .hi-orange[Imports] include goods and services *bought* from the rest of the world.


--

The difference between (1) and (2) is the country's .hi[trade balance].

  - It can also be called .hi[net exports]. ([`Official US data`](https://fred.stlouisfed.org/series/NETEXP).)


--

(3) .hi-orange[Income] transfers and payments include payments made to/received by one country for the use of *factors of production* (esp. labor and capital) used in a different country.

  - These include profits, wages, interest, and dividends.

--

(4) Lastly, .hi[unilateral transfer payments] involve local citizens or the local government sending remittances and/or humanitarian help to other countries, as well as foreigners making these transfers to the local nation.

  - These payments receive nothing in return.


---


# The balance of payments


.center[

.hi-orange[Net] exports + .hi-orange[Net] investment income + .hi-orange[Net] transfer payments = .hi[Balance on current account].

]

--

<br>

  - When money .hi[flows out] of a country, the operations receive a *negative* sign.
  
  - When money .hi[flows into] a country, the operations receive a *positive* sign.

--

<br>


The balance on current account will be .hi[negative] if a country has *spent* more on foreign goods and services, *sent out* investment income, and *made* more transfer payments than it has earned by *selling* goods and services, *receiving* investment income, and *receiving* transfer payments from abroad.

--

<br>

Otherwise, it will be .hi-orange[positive].


---

# The balance of payments


<br><br>

[`A look at official US data`](https://apps.bea.gov/iTable/?reqid=19&step=2&isuri=1&categories=survey#eyJhcHBpZCI6MTksInN0ZXBzIjpbMSwyLDNdLCJkYXRhIjpbWyJjYXRlZ29yaWVzIiwiU3VydmV5Il0sWyJOSVBBX1RhYmxlX0xpc3QiLCIxMjgiXV19)


--

<br>

[`Balance on current account chart`](https://fred.stlouisfed.org/series/NETFI)


---


# The balance of payments

The .hi-orange[financial] account is made of international *lending* and *borrowing*, as well as *asset sales*.

--

It has three main divisions:

  - .hi[Portfolio investment]: involves only *financial assets* (stocks, bonds, etc.)
  
  - .hi-orange[Foreign Direct Investment (FDI)]: involves changes in the control of *real* assets, such as land, buildings, or businesses.
  
  - .hi[Other investment]: involves mainly *new bank loans*.
  
--

<br>

In addition, the financial account may include .hi[foreign exchange reserves].

--

These include *foreign-currency assets* held by the country's .hi-orange[central bank].


---
layout: false
class: inverse, middle

# The US as a debtor nation


---

# The US as a debtor nation

A country's .hi-orange[net wealth position] will be determined by whether it has a .hi[positive] or .hi[negative] current account balance.

--

A country with .hi[positive] current account balance can be considered a .hi-orange[creditor] nation.

--

<br>

In the case of the US economy, it sustained a current account *surpluses* until mid-1970s.

  - A *creditor* nation!
  
--

Then, ever since, the US has become a *debtor* nation, showing successive current account deficits.

--

<br>

What does this fact imply?

---

layout: false
class: inverse, middle

# Next time: Aggregate demand & supply

---
exclude: true
